
# 通用配置
general_paras:
  output_dir: "ms_res/"

  random_seed: 0

  # Avg Krum FLtrust FedMs Ours
  defense: 'Avg'

  # 1.Noise 2.Random 3.SignFlip 4.Backward
  server_attacks: 'Backward'
  # 5. LabelFlip
  client_attacks: 'Backward'



defense_paras:
  Krum_m: 1
  alpha: 0.35
  gamma: 1
  beta: 0.35

attack_paras:

  server_is_attack: True
  client_is_attack: True
  SignFlipScaleFactor: -20    # used in SignFlip
  # 10 是不行的
  noise_std: 1
  noise_mean: 0
  random_lower: -10
  random_upper: 10
  LabelFlipRate: 0.4



dataset_paras:
 
  name: 'mnist'
  batch_size: 128
  save_path: 'data'
  normilizer: True
  num_workers: 24
  num_classes: 10


model_paras:


  # MLP
  name: 'MLP'


fed_paras:

  round: 40
  iid: False
  dirichlet_rate: 1
  server_number: 10
  client_number: 50
  server_attack_ratio: 0.1
  client_attack_ratio: 0.1
  generate_attacker: 'order'
  split_ratio: 0.9
  num_groups: 5   # indicate how much dataset
  

train_paras:
  # 0.001的比较好
  fltrust_global_lr: 0.2
  lr: 0.001
  optimizer_name: 'Adam'
  GPU: True
  cuda_number: 0
  epoch: 5
  criterion_name: 'CrossEntropy'


